ERROR - 2025-03-31 03:39:01 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2025-03-31 03:39:01 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 G:\My Drive\CodeIgniter4-4.1.9\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\My Drive\CodeIgniter4-4.1.9\system\Database\BaseBuilder.php(1588): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 G:\My Drive\CodeIgniter4-4.1.9\app\Models\Model2.php(51): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 G:\My Drive\CodeIgniter4-4.1.9\app\Controllers\Home.php(138): App\Models\Model2->getWhere('pengguna', Array)
#4 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(832): App\Controllers\Home->aksi_login()
#5 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 G:\My Drive\CodeIgniter4-4.1.9\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 G:\My Drive\CodeIgniter4-4.1.9\system\Commands\Server\rewrite.php(43): require_once('G:\\My Drive\\Cod...')
#9 {main}
CRITICAL - 2025-03-31 04:54:08 --> Invalid argument supplied for foreach()
#0 G:\My Drive\CodeIgniter4-4.1.9\app\Views\log_activity.php(8): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'G:\\My Drive\\Cod...', 8, Array)
#1 G:\My Drive\CodeIgniter4-4.1.9\system\View\View.php(210): include('G:\\My Drive\\Cod...')
#2 G:\My Drive\CodeIgniter4-4.1.9\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 G:\My Drive\CodeIgniter4-4.1.9\system\Common.php(1089): CodeIgniter\View\View->render('log_activity', Array, true)
#4 G:\My Drive\CodeIgniter4-4.1.9\app\Controllers\Home.php(618): view('log_activity', Array)
#5 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(832): App\Controllers\Home->viewLog()
#6 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\My Drive\CodeIgniter4-4.1.9\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 G:\My Drive\CodeIgniter4-4.1.9\system\Commands\Server\rewrite.php(43): require_once('G:\\My Drive\\Cod...')
#10 {main}
CRITICAL - 2025-03-31 04:54:10 --> Invalid argument supplied for foreach()
#0 G:\My Drive\CodeIgniter4-4.1.9\app\Views\log_activity.php(8): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'G:\\My Drive\\Cod...', 8, Array)
#1 G:\My Drive\CodeIgniter4-4.1.9\system\View\View.php(210): include('G:\\My Drive\\Cod...')
#2 G:\My Drive\CodeIgniter4-4.1.9\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 G:\My Drive\CodeIgniter4-4.1.9\system\Common.php(1089): CodeIgniter\View\View->render('log_activity', Array, true)
#4 G:\My Drive\CodeIgniter4-4.1.9\app\Controllers\Home.php(618): view('log_activity', Array)
#5 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(832): App\Controllers\Home->viewLog()
#6 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\My Drive\CodeIgniter4-4.1.9\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 G:\My Drive\CodeIgniter4-4.1.9\system\Commands\Server\rewrite.php(43): require_once('G:\\My Drive\\Cod...')
#10 {main}
CRITICAL - 2025-03-31 05:18:16 --> syntax error, unexpected 'public' (T_PUBLIC)
#0 G:\My Drive\CodeIgniter4-4.1.9\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('home/viewLog')
#1 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('home/viewLog')
#2 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\My Drive\CodeIgniter4-4.1.9\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 G:\My Drive\CodeIgniter4-4.1.9\system\Commands\Server\rewrite.php(43): require_once('G:\\My Drive\\Cod...')
#6 {main}
CRITICAL - 2025-03-31 06:36:59 --> Argument 2 passed to view() must be of the type array, null given, called in G:\My Drive\CodeIgniter4-4.1.9\app\Controllers\Home.php on line 635
#0 G:\My Drive\CodeIgniter4-4.1.9\app\Controllers\Home.php(635): view('header', NULL)
#1 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(832): App\Controllers\Home->pengaturan()
#2 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\My Drive\CodeIgniter4-4.1.9\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 G:\My Drive\CodeIgniter4-4.1.9\system\Commands\Server\rewrite.php(43): require_once('G:\\My Drive\\Cod...')
#6 {main}
CRITICAL - 2025-03-31 06:37:14 --> Argument 2 passed to view() must be of the type array, null given, called in G:\My Drive\CodeIgniter4-4.1.9\app\Controllers\Home.php on line 635
#0 G:\My Drive\CodeIgniter4-4.1.9\app\Controllers\Home.php(635): view('header', NULL)
#1 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(832): App\Controllers\Home->pengaturan()
#2 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 G:\My Drive\CodeIgniter4-4.1.9\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\My Drive\CodeIgniter4-4.1.9\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 G:\My Drive\CodeIgniter4-4.1.9\system\Commands\Server\rewrite.php(43): require_once('G:\\My Drive\\Cod...')
#6 {main}
ERROR - 2025-03-31 07:12:10 --> Unknown column 'owner' in 'field list'
ERROR - 2025-03-31 07:12:52 --> Unknown column 'owner' in 'field list'
ERROR - 2025-03-31 07:23:16 --> Unknown column 'id' in 'where clause'
ERROR - 2025-03-31 07:23:17 --> Unknown column 'id' in 'where clause'
